apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"kafka"},"name":"kafka","namespace":"social-network"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"kafka"}},"template":{"metadata":{"labels":{"app":"kafka"}},"spec":{"containers":[{"env":[{"name":"KAFKA_ZOOKEEPER_CONNECT","value":"zookeeper:2181"},{"name":"KAFKA_ADVERTISED_LISTENERS","value":"PLAINTEXT://kafka:9092"},{"name":"KAFKA_LISTENERS","value":"PLAINTEXT://0.0.0.0:9092"},{"name":"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR","value":"1"},{"name":"KAFKA_BROKER_ID","value":"1"},{"name":"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP","value":"PLAINTEXT:PLAINTEXT"},{"name":"KAFKA_INTER_BROKER_LISTENER_NAME","value":"PLAINTEXT"},{"name":"KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS","value":"30000"},{"name":"KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS","value":"30000"},{"name":"KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR","value":"1"},{"name":"KAFKA_TRANSACTION_STATE_LOG_MIN_ISR","value":"1"},{"name":"KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE","value":"false"}],"image":"confluentinc/cp-kafka:7.5.0","livenessProbe":{"exec":{"command":["kafka-topics","--bootstrap-server","localhost:9092","--list"]},"initialDelaySeconds":120,"periodSeconds":20,"timeoutSeconds":10},"name":"kafka","ports":[{"containerPort":9092}],"readinessProbe":{"exec":{"command":["kafka-topics","--bootstrap-server","localhost:9092","--list"]},"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/var/lib/kafka/data","name":"kafka-storage"}]}],"initContainers":[{"command":["sh","-c","chown -R 1000:1000 /var/lib/kafka/data"],"image":"busybox","name":"init-permissions","volumeMounts":[{"mountPath":"/var/lib/kafka/data","name":"kafka-storage"}]}],"volumes":[{"name":"kafka-storage","persistentVolumeClaim":{"claimName":"kafka-pvc"}}]}}}}
  creationTimestamp: "2026-01-07T14:21:02Z"
  generation: 15
  labels:
    app: kafka
  name: kafka
  namespace: social-network
  resourceVersion: "869537"
  uid: 996b54a3-b768-4c66-a27d-e1bb4616578e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-07T16:43:30+01:00"
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "30000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "30000"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        image: confluentinc/cp-kafka:7.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - kafka-topics
            - --bootstrap-server
            - localhost:9092
            - --list
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: kafka
        ports:
        - containerPort: 9092
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - kafka-topics
            - --bootstrap-server
            - localhost:9092
            - --list
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-storage
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /var/lib/kafka/data
        image: busybox
        imagePullPolicy: Always
        name: init-permissions
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-storage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
status:
  conditions:
  - lastTransitionTime: "2026-01-07T16:37:48Z"
    lastUpdateTime: "2026-01-07T16:37:48Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-01-07T16:17:33Z"
    lastUpdateTime: "2026-01-07T18:17:52Z"
    message: ReplicaSet "kafka-8577ff95dd" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 15
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
